name: build

on:
  pull_request:
    branches: [master]

env:
  DOTNET_VERSION: '9.x' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run:  dotnet test --no-restore --verbosity normal

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache-dependency-path: ./LocalShare/ClientApp/pnpm-lock.yaml
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ./LocalShare/ClientApp
        run: pnpm install

      - name: Prettier verify
        working-directory: ./LocalShare/ClientApp
        run: pnpm prettier-check

      # - name: Eslint verify
      #   working-directory: ./LocalShare/ClientApp
      #   run: npm run lint

      # - name: Test Vitest
      #   working-directory: ./LocalShare/ClientApp
      #   run: npm run test

      - name: Build Vite project
        working-directory: ./LocalShare/ClientApp
        run: pnpm build

      - name: Publish .NET app
        run: dotnet publish -c Release -o ./bin/Release

      - name: Start .NET app
        working-directory: ./
        run: dotnet ./bin/Release/LocalShare.dll --urls "https://localhost:5001" &

      - name: Run Playwright tests
        working-directory: ./LocalShare/ClientApp
        run: pnpm test-prod

