name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  DOTNET_VERSION: '9.x'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/setup-dotnet@v4
        with:
          node-version: lts/*
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        working-directory: ./LocalShare/ClientApp
        run: npm install -g pnpm && pnpm install

      - name: Install Playwright Browsers
        working-directory: ./LocalShare/ClientApp
        run: pnpm exec playwright install --with-deps

      - name: Install SSL Certificates
        run: |
          # Clean any old dev certs (allow to fail if no certs to clean)
          dotnet dev-certs https --clean || true
          
          # Ensure the target directory for the certificate exists
          mkdir -p $HOME/.aspnet/https
          
          # Create and export the certificate. Using a placeholder password.
          dotnet dev-certs https -ep $HOME/.aspnet/https/aspnetcore-dev.pfx -p P@ssw0rd1
          
          # Convert PFX to CRT (public certificate)
          openssl pkcs12 -in $HOME/.aspnet/https/aspnetcore-dev.pfx -clcerts -nokeys -out $HOME/.aspnet/https/aspnetcore-dev.crt -password pass:P@ssw0rd1
          
          # Copy the certificate to the system trust store and update
          sudo cp $HOME/.aspnet/https/aspnetcore-dev.crt /usr/local/share/ca-certificates/aspnetcore-dev.crt
          sudo update-ca-certificates

      - name: Publish .NET app
        working-directory: ./LocalShare
        run: dotnet publish -c Release -o ./bin/Release
      
      - name: Start .NET app
        working-directory: ./LocalShare
        run: dotnet ./bin/Release/LocalShare.dll --urls "https://localhost:5001" &

      - name: Run Playwright tests
        working-directory: ./LocalShare/ClientApp
        run: pnpm test-prod

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
